#!/usr/bin/env bash
#configuring nginx server
#+ Install Nginx if not already installed
sudo apt-get update && sudo apt-get install -y nginx

# Create a new Nginx configuration file
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Reload Nginx to apply the new configuration
sudo service nginx reload
